In [1]:
import os
import pandas as pd 
from dotenv import load_dotenv
from sqlalchemy import create_engine

In [2]:
load_dotenv()

user = os.getenv('PGUSER')
password = os.getenv('PGPASSWORD')
host = os.getenv('PGHOST')
port = os.getenv('PGPORT')
database = os.getenv('PGDATABASE')

engine = create_engine(F"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}")
engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/credit_risk)

In [3]:
pd.read_sql(
    "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';",
    engine
)

  table_name
0  loans_raw

In [4]:
# how big is it? 
TABLE = 'loans_raw'

pd.read_sql(
    f"SELECT COUNT(*) AS n_rows FROM {TABLE};", engine
)

    n_rows
0  2260701

In [5]:
from pathlib import Path

SAMPLE_PATH = Path("../data/processed/sample_50k.parquet")
FRACTION = 0.022

if SAMPLE_PATH.exists():
    df = pd.read_parquet(SAMPLE_PATH)
    print("loaded saved sample:", df.shape)
else:
    df = pd.read_sql(f"SELECT * FROM {TABLE} WHERE random() < {FRACTION};", engine)
    SAMPLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(SAMPLE_PATH, index=False)
    print("drew a new sample and saved it:", df.shape)

df.head()

drew a new sample and saved it: (49658, 151)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,66421727,None,25000.0,25000.0,25000.0,60 months,20.99,676.2,E,E5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,67287025,None,14725.0,14725.0,14725.0,60 months,11.22,321.78,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,67968292,None,9600.0,9600.0,9600.0,36 months,17.57,345.0,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,67858314,None,16000.0,16000.0,16000.0,36 months,16.55,566.87,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,67525862,None,19000.0,19000.0,19000.0,60 months,12.59,428.34,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
from pathlib import Path 

out_dir = Path("../data/processed")
out_dir.mkdir(parents=True, exist_ok=True)

df.to_parquet(out_dir / "sample_50k.parquet", index=False)
print('saved', df.shape)

saved (49658, 151)

In [7]:
df = pd.read_parquet("../data/processed/sample_50k.parquet")

In [8]:
df.dtypes.value_counts()

str       150
object      1
Name: count, dtype: int64

In [9]:
pd.set_option('display.max_rows', 200)
df.head(3).T

,0,1,2
id,66421727,67287025,67968292
member_id,None,None,None
loan_amnt,25000.0,14725.0,9600.0
funded_amnt,25000.0,14725.0,9600.0
funded_amnt_inv,25000.0,14725.0,9600.0
term,60 months,60 months,36 months
int_rate,20.99,11.22,17.57
installment,676.2,321.78,345.0
grade,E,B,D
sub_grade,E5,B5,D4
emp_title,Nurse,ast manager,team support specialist
emp_length,8 years,8 years,2 years
home_ownership,MORTGAGE,MORTGAGE,RENT
annual_inc,50000.0,40000.0,30000.0
verification_status,Not Verified,Not Verified,Verified
issue_d,Dec-2015,Dec-2015,Dec-2015
loan_status,Fully Paid,Fully Paid,Charged Off
pymnt_plan,n,n,n
url,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...,https://lendingclub.com/browse/loanDetail.acti...
desc,NaN,NaN,NaN
purpose,home_improvement,debt_consolidation,other
title,Home improvement,Debt consolidation,Other
zip_code,440xx,890xx,760xx
addr_state,OH,NV,TX
dti,17.83,21.87,19.48
delinq_2yrs,1.0,0.0,0.0
earliest_cr_line,Dec-2003,Oct-1976,Nov-2009
fico_range_low,710.0,770.0,665.0
fico_range_high,714.0,774.0,669.0
inq_last_6mths,0.0,0.0,1.0
mths_since_last_delinq,16.0,NaN,NaN
mths_since_last_record,NaN,NaN,NaN
open_acc,13.0,12.0,22.0
pub_rec,0.0,0.0,0.0
revol_bal,6502.0,49063.0,11621.0
revol_util,30.5,28.1,93.0
total_acc,30.0,14.0,27.0
initial_list_status,w,w,f
out_prncp,0.0,0.0,0.0
out_prncp_inv,0.0,0.0,0.0
total_pymnt,25206.99,17891.3289618108,4971.87
total_pymnt_inv,25206.99,17891.33,4971.87
total_rec_prncp,25000.0,14725.0,2660.81
total_rec_int,206.99,3166.33,1469.82
total_rec_late_fee,0.0,0.0,0.0
recoveries,0.0,0.0,841.24
collection_recovery_fee,0.0,0.0,151.4232
last_pymnt_d,Jan-2016,Apr-2018,Dec-2016
last_pymnt_amnt,25236.14,9492.93,345.0
next_pymnt_d,NaN,NaN,NaN
last_credit_pull_d,Feb-2019,Apr-2018,Jun-2017
last_fico_range_high,704.0,699.0,544.0
last_fico_range_low,700.0,695.0,540.0
collections_12_mths_ex_med,0.0,0.0,0.0
mths_since_last_major_derog,16.0,NaN,NaN
policy_code,1.0,1.0,1.0
application_type,Individual,Individual,Individual
annual_inc_joint,NaN,NaN,NaN
dti_joint,NaN,NaN,NaN
verification_status_joint,NaN,NaN,NaN
acc_now_delinq,0.0,0.0,0.0
tot_coll_amt,0.0,0.0,0.0
tot_cur_bal,29891.0,108419.0,64870.0
open_acc_6m,1.0,0.0,1.0
open_act_il,7.0,0.0,14.0
open_il_12m,2.0,0.0,1.0
open_il_24m,2.0,1.0,2.0
mths_since_rcnt_il,6.0,20.0,2.0
total_bal_il,23389.0,0.0,53249.0
il_util,66.0,NaN,118.0
open_rv_12m,0.0,1.0,0.0
open_rv_24m,0.0,2.0,4.0
max_bal_bc,4502.0,3986.0,4224.0
all_util,53.0,28.0,112.0
total_rev_hi_lim,21300.0,76800.0,12500.0
inq_fi,3.0,1.0,2.0
total_cu_tl,6.0,0.0,0.0
inq_last_12m,13.0,0.0,3.0
acc_open_past_24mths,2.0,3.0,6.0
avg_cur_bal,2299.0,12047.0,2949.0
bc_open_to_buy,14798.0,26454.0,879.0
bc_util,30.5,28.1,93.0
chargeoff_within_12_mths,0.0,0.0,0.0
delinq_amnt,0.0,0.0,0.0
mo_sin_old_il_acct,135.0,20.0,73.0
mo_sin_old_rev_tl_op,130.0,470.0,27.0
mo_sin_rcnt_rev_tl_op,29.0,10.0,18.0
mo_sin_rcnt_tl,6.0,10.0,2.0
mort_acc,2.0,1.0,0.0
mths_since_recent_bc,29.0,10.0,18.0
mths_since_recent_bc_dlq,NaN,NaN,NaN
mths_since_recent_inq,1.0,20.0,2.0
mths_since_recent_revol_delinq,NaN,NaN,NaN
num_accts_ever_120_pd,1.0,0.0,0.0
num_actv_bc_tl,2.0,7.0,8.0
num_actv_rev_tl,2.0,8.0,8.0
num_bc_sats,6.0,7.0,8.0
num_bc_tl,7.0,8.0,8.0
num_il_tl,20.0,1.0,19.0
num_op_rev_tl,6.0,11.0,8.0
num_rev_accts,8.0,12.0,8.0
num_rev_tl_bal_gt_0,2.0,8.0,8.0
num_sats,13.0,12.0,22.0
num_tl_120dpd_2m,0.0,0.0,0.0
num_tl_30dpd,0.0,0.0,0.0
num_tl_90g_dpd_24m,1.0,0.0,0.0
num_tl_op_past_12m,2.0,1.0,1.0
pct_tl_nvr_dlq,96.7,100.0,100.0
percent_bc_gt_75,16.7,14.3,87.5
pub_rec_bankruptcies,0.0,0.0,0.0
tax_liens,0.0,0.0,0.0
tot_hi_cred_lim,56938.0,140800.0,57778.0
total_bal_ex_mort,29891.0,49063.0,64870.0
total_bc_limit,21300.0,36800.0,12500.0
total_il_high_credit_limit,35638.0,0.0,45278.0
revol_bal_joint,NaN,NaN,NaN
sec_app_fico_range_low,NaN,NaN,NaN
sec_app_fico_range_high,NaN,NaN,NaN
sec_app_earliest_cr_line,NaN,NaN,NaN
sec_app_inq_last_6mths,NaN,NaN,NaN
sec_app_mort_acc,NaN,NaN,NaN
sec_app_open_acc,NaN,NaN,NaN
sec_app_revol_util,NaN,NaN,NaN
sec_app_open_act_il,NaN,NaN,NaN
sec_app_num_rev_accts,NaN,NaN,NaN
sec_app_chargeoff_within_12_mths,NaN,NaN,NaN
sec_app_collections_12_mths_ex_med,NaN,NaN,NaN
sec_app_mths_since_last_major_derog,NaN,NaN,NaN
hardship_flag,N,N,N
hardship_type,NaN,NaN,NaN
hardship_reason,NaN,NaN,NaN
hardship_status,NaN,NaN,NaN
deferral_term,NaN,NaN,NaN
hardship_amount,NaN,NaN,NaN
hardship_start_date,NaN,NaN,NaN
hardship_end_date,NaN,NaN,NaN
payment_plan_start_date,NaN,NaN,NaN
hardship_length,NaN,NaN,NaN
hardship_dpd,NaN,NaN,NaN
hardship_loan_status,NaN,NaN,NaN
orig_projected_additional_accrued_interest,NaN,NaN,NaN
hardship_payoff_balance_amount,NaN,NaN,NaN
hardship_last_payment_amount,NaN,NaN,NaN
disbursement_method,Cash,Cash,Cash
debt_settlement_flag,N,N,N
debt_settlement_flag_date,NaN,NaN,NaN
settlement_status,NaN,NaN,NaN
settlement_date,NaN,NaN,NaN
settlement_amount,NaN,NaN,NaN
settlement_percentage,NaN,NaN,NaN
settlement_term,NaN,NaN,NaN

In [10]:
empty_share = df.isna().mean().sort_values(ascending=False)
empty_share.head(40)

member_id                                     1.000000
orig_projected_additional_accrued_interest    0.996214
hardship_reason                               0.995288
hardship_payoff_balance_amount                0.995288
hardship_last_payment_amount                  0.995288
payment_plan_start_date                       0.995288
hardship_type                                 0.995288
hardship_status                               0.995288
hardship_start_date                           0.995288
deferral_term                                 0.995288
hardship_amount                               0.995288
hardship_dpd                                  0.995288
hardship_loan_status                          0.995288
hardship_length                               0.995288
hardship_end_date                             0.995288
settlement_status                             0.984796
debt_settlement_flag_date                     0.984796
settlement_term                               0.984796
settlement_percentage                         0.984796
settlement_date                               0.984796
settlement_amount                             0.984796
sec_app_mths_since_last_major_derog           0.983829
sec_app_revol_util                            0.954267
sec_app_num_rev_accts                         0.953341
sec_app_earliest_cr_line                      0.953341
sec_app_mort_acc                              0.953341
sec_app_open_acc                              0.953341
revol_bal_joint                               0.953341
sec_app_fico_range_low                        0.953341
sec_app_open_act_il                           0.953341
sec_app_inq_last_6mths                        0.953341
sec_app_fico_range_high                       0.953341
sec_app_collections_12_mths_ex_med            0.953341
sec_app_chargeoff_within_12_mths              0.953341
verification_status_joint                     0.949716
annual_inc_joint                              0.947783
dti_joint                                     0.947783
desc                                          0.943594
mths_since_last_record                        0.838838
mths_since_recent_bc_dlq                      0.768094
dtype: float64